### ISSUE TITLE
【質問】インストールについて

### ISSUE THREAD

**Issue by mumei-xxxx** [yukikurage/purescript-jelly#19]
すみません。

purescript-jellyのインストールがうまくいかず、以下の手順で、間違っている、欠けているものがあれば、ご教示いただいてよろしいでしょうか。

## 行った手順

```
spago init
```

で初期化。

packages.dhall

にドキュメント[ https://jelly.yukikurage.net/docs/installation/ ]の記述を記載。

```
spago install jelly
```
以下のエラーが出ました。
```
[error] The following packages do not exist in your package set:
[error]   - affjax-web
```
affjax-webをインストールしようとして、
```
spago install affjax-web
```

やはり、以下のエラーがでて、インストールできません。

```
[error] The following packages do not exist in your package set:
[error]   - affjax-web
```

**Comment by yukikurage** [comment]
package-set のバージョンが古い可能性があります
```
 spago upgrade-set
```
を実行してから再び試してみてください

**Comment by mumei-xxxx** [comment]
ご回答いただきありがとうございます。
返信が遅れ申し訳ありません。
` spago upgrade-set` なども実行し、原因を再度、調査したところ、PureScript自体のバージョンが古かったのが原因のようでした。
PureScriptのバージョンをv0.14.x から v0.15.4へ上げたところ、正常にインストールできました。
お手数をおかけして申し訳ありませんでした。
ありがとうございます。

解決いたしましたので、issue 閉じさせていただきます。
